server:
  port: 3344
spring:
  application:
    name: springcloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yangqx/springcloud-config.git

# eureka
#eureka:
#  client:
#    service-url:
#      #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
#      defaultZone: http://eureka7001.com:7001/eureka/
#  instance:
#    instance-id: springclould-provider-dept8001
#    prefer-ip-address: true #显示ip
## info
#info:
#  app.name: yangqx-springcloud
#  company.name: tflx.com